"""Initial migration

Revision ID: e89d406a6dce
Revises: 
Create Date: 2021-01-17 22:20:13.266397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89d406a6dce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foodcity')
    op.drop_constraint('restaurants_city_key', 'restaurants', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('restaurants_city_key', 'restaurants', ['city'])
    op.create_table('foodcity',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('food', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='foodcity_pkey')
    )
    # ### end Alembic commands ###
